# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='rate',
            field=models.CharField(default='****', max_length=10),
            preserve_default=False,
        ),
    ]
