# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-18 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_boardgame_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
