# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-20 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180818_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='bgg_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='rate',
            field=models.FloatField(default=5, null=True),
        ),
    ]
