# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-09-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20180820_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('timestamp', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('evand_frame', models.TextField()),
            ],
        ),
    ]
