# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-01 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
