# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-01 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('evand_frame', models.TextField()),
            ],
        ),
    ]
